[Service]
Environment=WORKER_NAME=daystrom_watch
Environment=CUDA_VISIBLE_DEVICES=0
Environment=EXEC_TOKEN=changeme3
Environment=JOBS_ROOT=/mnt/collective/jobs
Environment=JOBS_OUT_ROOT=/mnt/collective/jobs_out
