[Service]
Environment=WORKER_NAME=daystrom_exec
Environment=CUDA_VISIBLE_DEVICES=1
Environment=EXEC_TOKEN=changeme2
Environment=JOBS_ROOT=/mnt/collective/jobs
Environment=JOBS_OUT_ROOT=/mnt/collective/jobs_out
